export const GET_CHARACTERS = 'GET_CHARACTERS';
export const GET_CHARACTERS_SUCCESS = 'GET_CHARACTERS_SUCCESS';
export const GET_CHARACTERS_ERROR = 'GET_CHARACTERS_ERROR';

export const GET_FILTERS = 'GET_FILTERS';
export const GET_FILTERS_ERROR = 'GET_FILTERS_ERROR';
export const GET_FILTERS_SUCCESS = 'GET_FILTERS_SUCCESS';

export const REMOVE_FILTERED = 'REMOVE_FILTERED';

export const UPDATE_PAGE = 'UPDATE_PAGE';

export const SET_SEARCH = 'SET_SEARCH';