export const GET_EPISODES: string = 'GET_EPISODES';
export const GET_EPISODES_SUCCESS: string = 'GET_EPISODES_SUCCESS';
export const GET_EPISODES_ERROR: string = 'GET_EPISODES_ERROR';

export const GET_FILTERS_EPISODES: string = 'GET_FILTERS_EPISODES';
export const GET_FILTERS_EPISODES_ERROR: string = 'GET_FILTERS_EPISODES_ERROR';
export const GET_FILTERS_EPISODES_SUCCESS: string = 'GET_FILTERS_EPISODES_SUCCESS';

export const REMOVE_FILTERED_EPISODE: string = 'REMOVE_FILTERED_EPISODE';

export const UPDATE_PAGE_EPISODE: string = 'UPDATE_PAGE_EPISODE';

export const SET_SEARCH_EP: string = 'SET_SEARCH_EP';