export const GET_EPISODES = 'GET_EPISODES';
export const GET_EPISODES_SUCCESS = 'GET_EPISODES_SUCCESS';
export const GET_EPISODES_ERROR = 'GET_EPISODES_ERROR';

export const GET_FILTERS_EPISODES = 'GET_FILTERS_EPISODES';
export const GET_FILTERS_EPISODES_ERROR = 'GET_FILTERS_EPISODES_ERROR';
export const GET_FILTERS_EPISODES_SUCCESS = 'GET_FILTERS_EPISODES_SUCCESS';

export const REMOVE_FILTERED = 'REMOVE_FILTERED';

export const UPDATE_PAGE_EPISODE = 'UPDATE_PAGE_EPISODE';

export const SET_SEARCH_EP = 'SET_SEARCH_EP';