export const GET_LOCATIONS = 'GET_LOCATIONS';
export const GET_LOCATIONS_SUCCESS = 'GET_LOCATIONS_SUCCESS';
export const GET_LOCATIONS_ERROR = 'GET_LOCATIONS_ERROR';

export const GET_LOCATIONS_FILTERS = 'GET_LOCATIONS_FILTERS';
export const GET_LOCATIONS_FILTERS_ERROR = 'GET_LOCATIONS_FILTERS_ERROR';
export const GET_LOCATIONS_FILTERS_SUCCESS = 'GET_LOCATIONS_FILTERS_SUCCESS';

export const REMOVE_FILTERED_LOCATION = 'REMOVE_FILTERED_LOCATION';

export const UPDATE_PAGE_LOCATIONS = 'UPDATE_PAGE_LOCATIONS';

export const SET_SEARCH_LOC = 'SET_SEARCH_LOC';