export const GET_LOCATIONS: string = 'GET_LOCATIONS';
export const GET_LOCATIONS_SUCCESS: string = 'GET_LOCATIONS_SUCCESS';
export const GET_LOCATIONS_ERROR: string = 'GET_LOCATIONS_ERROR';

export const GET_LOCATIONS_FILTERS: string = 'GET_LOCATIONS_FILTERS';
export const GET_LOCATIONS_FILTERS_ERROR: string = 'GET_LOCATIONS_FILTERS_ERROR';
export const GET_LOCATIONS_FILTERS_SUCCESS: string = 'GET_LOCATIONS_FILTERS_SUCCESS';

export const REMOVE_FILTERED_LOCATION: string = 'REMOVE_FILTERED_LOCATION';

export const UPDATE_PAGE_LOCATIONS: string = 'UPDATE_PAGE_LOCATIONS';

export const SET_SEARCH_LOC: string = 'SET_SEARCH_LOC';